export const PROVINCES_34 = [
  "Tuyên Quang",
  "Cao Bằng",
  "Lai Châu",
  "Lào Cai",
  "Thái Nguyên",
  "Điện Biên",
  "Lạng Sơn",
  "Sơn La",
  "Phú Thọ",
  "Bắc Ninh",
  "Quảng Ninh",
  "TP. Hà Nội",
  "TP. Hải Phòng",
  "Hưng Yên",
  "Ninh Bình",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Trị",
  "TP. Huế",
  "TP. Đà Nẵng",
  "Quảng Ngãi",
  "Gia Lai",
  "Đắk Lắk",
  "Khánh Hoà",
  "Lâm Đồng",
  "Đồng Nai",
  "Tây Ninh",
  "TP. Hồ Chí Minh",
  "Đồng Tháp",
  "An Giang",
  "Vĩnh Long",
  "TP. Cần Thơ",
  "Cà Mau"
];
