export const COUNTRY_MAP: Record<string, string> = {
  'Qatar': 'qa', 'Switzerland': 'ch', 'Brazil': 'br', 'Morocco': 'ma',
  'Japan': 'jp', 'Spain': 'es', 'Germany': 'de', 'Croatia': 'hr',
  'Argentina': 'ar', 'Australia': 'au', 'Senegal': 'sn', 'England': 'gb-eng',
  'France': 'fr', 'Poland': 'pl', 'Netherlands': 'nl', 'USA': 'us',
  'Portugal': 'pt', 'South Korea': 'kr', 'Korea Republic': 'kr', 'Saudi Arabia': 'sa', 'Mexico': 'mx',
  'Iran': 'ir', 'Tunisia': 'tn', 'Cameroon': 'cm', 'Uruguay': 'uy',
  'Ecuador': 'ec', 'Canada': 'ca', 'Ghana': 'gh', 'Belgium': 'be',
  'Serbia': 'rs', 'Costa Rica': 'cr', 'Wales': 'gb-wls', 'Denmark': 'dk',
  'Türkiye': 'tr', 'Turkey': 'tr', 'Paraguay': 'py', 'Chile': 'cl',
  'Colombia': 'co', 'Peru': 'pe', 'Venezuela': 've', 'Bolivia': 'bo',
  'Italy': 'it', 'Sweden': 'se', 'Norway': 'no', 'Finland': 'fi',
  'Scotland': 'gb-sct', 'Ireland': 'ie', 'Northern Ireland': 'gb-nir',
  'Ukraine': 'ua', 'Czech Republic': 'cz', 'Austria': 'at', 'Hungary': 'hu',
  'Romania': 'ro', 'Greece': 'gr', 'Slovakia': 'sk', 'Slovenia': 'si',
  'Egypt': 'eg', 'Nigeria': 'ng', 'Algeria': 'dz', 'Ivory Coast': 'ci',
  'Mali': 'ml', 'South Africa': 'za', 'China': 'cn', 'India': 'in',
  'New Zealand': 'nz', 'Haiti': 'ht', 'Curaçao': 'cw', 'Jamaica': 'jm',
  'Panama': 'pa', 'Honduras': 'hn', 'El Salvador': 'sv', 'Iraq': 'iq',
  'UAE': 'ae', 'Oman': 'om', 'Bahrain': 'bh', 'Jordan': 'jo', 'Syria': 'sy',
  'Palestine': 'ps', 'Lebanon': 'lb', 'Uzbekistan': 'uz', 'Vietnam': 'vn',
  'Thailand': 'th', 'Indonesia': 'id', 'Malaysia': 'my', 'Singapore': 'sg',
  'Philippines': 'ph', 'Myanmar': 'mm', 'Cambodia': 'kh', 'Laos': 'la',
  'Brunei': 'bn', 'Timor-Leste': 'tl', 'Iceland': 'is', 'Georgia': 'ge',
  'Armenia': 'am', 'Azerbaijan': 'az', 'Kazakhstan': 'kz', 'Israel': 'il',
  'Albania': 'al', 'Bosnia & Herzegovina': 'ba', 'Montenegro': 'me',
  'North Macedonia': 'mk', 'Cyprus': 'cy', 'Moldova': 'md', 'Lithuania': 'lt',
  'Latvia': 'lv', 'Estonia': 'ee', 'Bulgaria': 'bg', 'Kosovo': 'xk'
};
